INSERT INTO MEDICINE (ID, FIRST_NAME,LAST_NAME,MIDDLE_NAME,OCCUPATION,AGE,DOB, CREATED_ON, UPDATED_ON) VALUES (1, 'Steve','Zemanick','Michael','IT',17, parsedatetime('17-09-2012', 'dd-MM-yyyy'), now(), now());
INSERT INTO MEDICINE (ID, FIRST_NAME,LAST_NAME,MIDDLE_NAME,OCCUPATION,AGE,DOB, CREATED_ON, UPDATED_ON) VALUES (2, 'Jim','Zemanick','','Accounting',23, parsedatetime('17-09-2012', 'dd-MM-yyyy'), now(), now());
INSERT INTO MEDICINE (ID, FIRST_NAME,LAST_NAME,MIDDLE_NAME,OCCUPATION,AGE,DOB, CREATED_ON, UPDATED_ON) VALUES (3, 'Peter','Harrison','Q','Accounting',34, parsedatetime('17-09-2012', 'dd-MM-yyyy'), now(), now());
INSERT INTO MEDICINE (ID, FIRST_NAME,LAST_NAME,MIDDLE_NAME,OCCUPATION,AGE,DOB, CREATED_ON, UPDATED_ON) VALUES (4, 'Tom','Hill','','Accounting',54, parsedatetime('17-09-2012', 'dd-MM-yyyy'), now(), now());
INSERT INTO MEDICINE (ID, FIRST_NAME,LAST_NAME,MIDDLE_NAME,OCCUPATION,AGE,DOB, CREATED_ON, UPDATED_ON) VALUES (5, 'Joe','Jones','','IT',56, parsedatetime('17-09-2012', 'dd-MM-yyyy'), now(), now());
INSERT INTO MEDICINE (ID, FIRST_NAME,LAST_NAME,MIDDLE_NAME,OCCUPATION,AGE,DOB, CREATED_ON, UPDATED_ON) VALUES (6, 'Harry','Smith','','IT',34, parsedatetime('17-09-2012', 'dd-MM-yyyy'), now(), now());
INSERT INTO MEDICINE (ID, FIRST_NAME,LAST_NAME,MIDDLE_NAME,OCCUPATION,AGE,DOB, CREATED_ON, UPDATED_ON) VALUES (7, 'Mark','Jones','','IT',65, parsedatetime('17-09-2012', 'dd-MM-yyyy'), now(), now());
INSERT INTO MEDICINE (ID, FIRST_NAME,LAST_NAME,MIDDLE_NAME,OCCUPATION,AGE,DOB, CREATED_ON, UPDATED_ON) VALUES (8, 'Rob','Smith','','IT',31, parsedatetime('17-09-2012', 'dd-MM-yyyy'), now(), now());


